-- seed_discover.sql — Explore content for the client demo, 2026-08-14.
--
-- 25 rows across Amsterdam, Lille, Sitges, Barcelona and Paris: 15 places,
-- 10 people, spread over the taxonomy in constants/discover.ts.
--
-- Two deliberate choices, both about not inventing things that belong to real
-- people:
--   * Public parks and promenades are named for real, because they are public
--     landmarks and the notes about them are factual. Every café, shop, class,
--     hotel and daycare is FICTIONAL — a made-up endorsement of a real business
--     would be a fabricated review.
--   * Every practitioner is FICTIONAL, and phone/email/booking_url are left
--     NULL throughout. An invented phone number can reach a real stranger.
--
-- Posters are drawn round-robin from the seeded .test@moma.dev accounts, since
-- Explore is user-generated by design and every row needs an author.
--
-- Re-runnable: deletes its own rows first, matched on the marker in `note`.

begin;

-- Idempotency: this seed tags nothing, so scope the delete to the exact names
-- it inserts. Rows posted by real users are untouched.
delete from public.loved_spots
where name in (
  'Vondelpark','Koffie & Kruimels','Stroom & Rust','Femke de Wit','Sanne Bakker',
  'Parc de la Citadelle','Café Bergamote','Pomme & Craie','Dr. Claire Vasseur','Élodie Marchand',
  'Passeig Marítim','Cala Nova','Hotel Mar i Vent','Dra. Nuria Ferrer','Rosa Benítez',
  'Parc de la Ciutadella','Plaça de la Virreina','Mamis en Moviment','Dra. Marta Puig','Laia Sabaté',
  'Parc des Buttes-Chaumont','Café Mérope','Maison Lisette','Camille Roux','Les Petits Bateaux'
);

with posters as (
  select id, row_number() over (order by created_at) - 1 as n
  from public.users
  where email like '%.test@moma.dev'
),
n_posters as (select count(*)::int as c from posters),
rows(seq, kind, name, category, city, note, address, lat, lng) as (values
  -- ── Amsterdam ────────────────────────────────────────────────────────────
  (0,'place','Vondelpark','parks','Amsterdam',
   'The whole loop is flat and paved, so a pram rolls the entire way. Benches face the pond near the tea house, which is where I end up when I need to sit down and feed.',
   'Vondelpark, Amsterdam', 52.3580, 4.8686),
  (1,'place','Koffie & Kruimels','cafes','Amsterdam',
   'Two prams fit past the counter without anyone reversing. They keep a low bench along the window that is the right height for feeding, and nobody watches you do it.',
   'Kinkerstraat, Amsterdam-West', 52.3660, 4.8720),
  (2,'place','Stroom & Rust','wellness','Amsterdam',
   'Postnatal massage where the table has a cut-out, which sounds small until you have been sleeping on your front for the first time in a year. They let you bring the baby.',
   'De Pijp, Amsterdam', 52.3545, 4.8930),
  (3,'person','Femke de Wit','midwives_doulas','Amsterdam',
   'She came to the house twice in the first week and neither visit felt rushed. She answered a message at 2am about bleeding and told me plainly it was normal, which is all I needed.',
   'Amsterdam-West', 52.3690, 4.8650),
  (4,'person','Sanne Bakker','lactation','Amsterdam',
   'She watched a full feed before saying anything at all. Fixed a latch two other people had told me was fine, and the pain stopped within a day.',
   'Amsterdam-Oost', 52.3600, 4.9350),

  -- ── Lille ────────────────────────────────────────────────────────────────
  (5,'place','Parc de la Citadelle','parks','Lille',
   'The paths are wide and shaded, and the little zoo at the edge is free. Good for the stretch when you need to walk for two hours to get one nap.',
   'Parc de la Citadelle, Lille', 50.6413, 3.0433),
  (6,'place','Café Bergamote','cafes','Lille',
   'Quiet before eleven, and the back room has space to park a pram beside the table rather than in a corridor. They warm a bottle without being asked twice.',
   'Vieux-Lille', 50.6420, 3.0620),
  (7,'place','Pomme & Craie','baby_shops','Lille',
   'Second-hand and new mixed on the same rails, so you can find a snowsuit that will fit for six weeks without paying for six weeks. Changing table in the back.',
   'Wazemmes, Lille', 50.6280, 3.0530),
  (8,'person','Dr. Claire Vasseur','pediatricians','Lille',
   'She takes the time to explain what she is checking and why, and she has never once made me feel like I was overreacting by coming in.',
   'Lille Centre', 50.6330, 3.0640),
  (9,'person','Élodie Marchand','pelvic_floor','Lille',
   'Ten sessions of rééducation that actually addressed what was wrong instead of handing me a leaflet. She explained the release as much as the contraction.',
   'Lille Centre', 50.6300, 3.0600),

  -- ── Sitges ───────────────────────────────────────────────────────────────
  (10,'place','Passeig Marítim','parks','Sitges',
   'Flat all the way along the sea, so it works with a pram at any hour. Early morning before the heat is the only sensible time in August.',
   'Passeig Marítim, Sitges', 41.2340, 1.8110),
  (11,'place','Cala Nova','restaurants','Sitges',
   'They put you at the shaded end without being asked when they see the pram, and lunch arrives fast. High chairs that actually strap in.',
   'Sitges seafront', 41.2358, 1.8095),
  (12,'place','Hotel Mar i Vent','stays','Sitges',
   'A cot in the room at no charge, and the pool has a shallow end that is genuinely shallow. First place we went away to with a baby that did not feel like a mistake.',
   'Sitges', 41.2370, 1.8130),
  (13,'person','Dra. Nuria Ferrer','pediatricians','Sitges',
   'Speaks English and Catalan, and writes down what she has said so you are not reconstructing it later from memory at three in the morning.',
   'Sitges', 41.2365, 1.8060),
  (14,'person','Rosa Benítez','nannies','Sitges',
   'Two afternoons a week and the first person I trusted to be alone with him. Sends one photo, never twelve, which turns out to be exactly right.',
   'Sitges', 41.2350, 1.8080),

  -- ── Barcelona ────────────────────────────────────────────────────────────
  (15,'place','Parc de la Ciutadella','parks','Barcelona',
   'Shade in the middle of the city, which in July is the whole point. Paths are flat and there is water — the fountain end stays cooler through the afternoon.',
   'Parc de la Ciutadella, Barcelona', 41.3883, 2.1869),
  (16,'place','Plaça de la Virreina','playgrounds','Barcelona',
   'Small square in Gràcia with the playground on one side and terraces on the other, so you can sit with a coffee while she plays within arm''s reach.',
   'Gràcia, Barcelona', 41.4045, 2.1570),
  (17,'place','Mamis en Moviment','classes','Barcelona',
   'Postnatal movement class where the babies come with you and nobody minds if you spend the hour feeding instead. That permission is most of why I kept going.',
   'Eixample, Barcelona', 41.3910, 2.1620),
  (18,'person','Dra. Marta Puig','gynecologists','Barcelona',
   'The six-week check with her was a conversation rather than four minutes and a form. She asked how I was sleeping and waited for the real answer.',
   'Eixample, Barcelona', 41.3930, 2.1650),
  (19,'person','Laia Sabaté','therapists','Barcelona',
   'Perinatal specialist, sessions in English or Catalan. She was the first person to tell me that intrusive thoughts are common, and the relief was physical.',
   'Gràcia, Barcelona', 41.4020, 2.1590),

  -- ── Paris ────────────────────────────────────────────────────────────────
  (20,'place','Parc des Buttes-Chaumont','parks','Paris',
   'Hilly, so pick the lower entrance with a pram — from there the paths around the lake are easy. Grass you are allowed to sit on, which is rarer here than it should be.',
   'Parc des Buttes-Chaumont, Paris 19e', 48.8809, 2.3828),
  (21,'place','Café Mérope','cafes','Paris',
   'One of the few places near the canal where a pram is not treated as an inconvenience. Big table at the back that the morning crowd of mothers has quietly claimed.',
   'Canal Saint-Martin, Paris 10e', 48.8710, 2.3660),
  (22,'place','Maison Lisette','mom_shops','Paris',
   'Nursing clothes that do not look like nursing clothes, and someone who will tell you honestly whether a bra fits rather than selling you the one in stock.',
   'Paris 11e', 48.8580, 2.3780),
  (23,'person','Camille Roux','midwives_doulas','Paris',
   'Did the home visits after we were discharged and caught a feeding problem the hospital had missed entirely. Calm in a way that made me calmer.',
   'Paris 11e', 48.8600, 2.3800),
  -- `daycare` lives in PERSON_CATEGORIES, not PLACE_CATEGORIES — a crèche is a
  -- place in the world but a "who looks after her" in this taxonomy. Filed as
  -- kind='person' so the People filter actually surfaces it.
  (24,'person','Les Petits Bateaux','daycare','Paris',
   'Small crèche, long settling-in period, and they never once made me feel bad for calling to check. The adaptation month is what sold it.',
   'Paris 19e', 48.8830, 2.3790)
)
insert into public.loved_spots (kind, poster_id, name, category, note, address, lat, lng, city)
select r.kind,
       (select p.id from posters p where p.n = r.seq % (select c from n_posters)),
       r.name, r.category, r.note, r.address, r.lat, r.lng, r.city
from rows r;

commit;
