-- 029_brought_items.sql
-- Bring something to the table. One thing per mom, on her profile, visible to
-- everyone at her table.
--
-- Applied via the `brought_items` migration; this file is the record. Adds the
-- table, shares_group_with(), and brought_for_users().
--
-- Five kinds whose fields differ enough that a column per field would be mostly
-- nulls, so the shape lives in `payload` and is validated in the app — the same
-- bet as the Explore taxonomy, and for the same reason: both will keep moving.
--
-- What the DB does guarantee is the part the product rests on: ONE row per mom.
-- Bringing something else REPLACES what's there and the old one is not kept —
-- the client chose that over a history, so the composer warns before it happens.
--
-- Reach: yours, plus the tables you sit at. Deliberately not world-readable. A
-- Discover contributor's page is open to moms who share no group with her, and
-- what you bring to your table shouldn't end up in a shop window.
